name: build-and-push

on:
    push:
        branches:
            - master
        paths:
            - Dockerfile
            - requirements.txt
    pull_request:
        paths:
            - Dockerfile
            - requirements.txt
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                alpine-version: ["3.13", "3.14", "3.15"]
                python-version: [3.7, 3.8, 3.9]
        env:
            IMAGE_NAME: rushilsrivastava/python-grpcio-alpine
        outputs:
            image-tags: ${{ env.IMAGE_NAME }}:${{ steps.docker_meta.outputs.version }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Cache Docker layers
              uses: actions/cache@v2
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-

            - name: Login to Docker Hub
              if: github.event_name != 'pull_request'
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push (pr)
              if: ${{ github.event_name == 'pull_request' }}
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  build-args: |
                      PYTHON_VERSION=${{ matrix.python-version }}
                      ALPINE_VERSION=${{ matrix.alpine-version }}
                  tags: ${{ IMAGE_NAME }}:${{ github.sha }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache
                  outputs: type=docker,dest=/tmp/python-alpine-grpcio-${{ github.sha }}.tar

            - name: Upload artifact (pr)
              if: ${{ github.event_name == 'pull_request' }}
              uses: actions/upload-artifact@v2
              with:
                  name: docker-image
                  path: /tmp/python-alpine-grpcio-${{ github.sha }}.tar
                  retention-days: 1

            - name: Build and push (branch)
              if: ${{ github.event_name != 'pull_request' }}
              uses: docker/build-push-action@v2
              with:
                  context: .
                  push: true
                  # platforms: linux/amd64,linux/arm64
                  build-args: |
                      PYTHON_VERSION=${{ matrix.python-version }}
                      ALPINE_VERSION=${{ matrix.alpine-version }}
                  tags: ${{ IMAGE_NAME }}:${{ matrix.python-version }}-${{ cat requirements.txt | cut -d'=' -f 3 }}-${{ matrix.alpine-version }}, ${{ IMAGE_NAME }}:${{ github.sha }}
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache
